/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExceptionHandling */

#ifndef _Included_ExceptionHandling
#define _Included_ExceptionHandling
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ExceptionHandling
 * Method:    ExceptionDemo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ExceptionHandling_ExceptionDemo
  (JNIEnv *, jobject);

/*
 * Class:     ExceptionHandling
 * Method:    FatalErrorDemo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ExceptionHandling_FatalErrorDemo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
